"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),storage=new Map();
const context={console,Intl,Date,Math,setTimeout,clearTimeout,setInterval,clearInterval,localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,String(value)),removeItem:key=>storage.delete(key)},document:{getElementById:id=>id==="toast-region"?{appendChild:()=>{}}:{},querySelectorAll:()=>[],createElement:()=>({remove:()=>{}})},navigator:{},addEventListener:()=>{},__test:{}};
context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,"data/dongqiudi-data.js"),"utf8"),context);
let source=fs.readFileSync(path.join(root,"app.js"),"utf8");source=source.replace("  function render() {\n","  function render() { return; }\n  function renderDisabled() {\n");source=source.replace(/\n  render\(\);\n\}\)\(\);\s*$/,`\n  Object.assign(window.__test,{APP_VERSION,CLUBS,createSquad,ensurePlayerContract,createCoachCareer,ensureCoachCareer,COACH_STORY_EVENTS,applyCoachCareerDay,resolveCoachStoryChoice,coachMatchEffect,teamOverallStrength,matchSelectionScore,setTestState:value=>{state=value;}});\n})();\n`);vm.runInContext(source,context);

const api=context.__test,club=api.CLUBS[0],squad=api.createSquad(club,null);squad.forEach(player=>api.ensurePlayerContract(player,2026));
const fixture={id:"coach-event-fixture",date:"2026-08-10",competition:"英超",round:"第 1 轮",opponent:api.CLUBS[1].name,home:true,status:"upcoming"};
const state={version:40,role:"coach",person:"V1.5 Test Coach",clubId:club.id,squad,season:2026,date:"2026-08-03",view:"home",funds:100,training:"balanced",tactic:"balanced",schedule:[fixture],played:0,wins:0,draws:0,losses:0,points:0,leaguePosition:1,notifications:[],media:[],honors:[],history:[],transferHistory:[],transferRequestsLog:[],transferNegotiations:[],coachCareer:null,coachProfile:{name:"V1.5 Test Coach",overall:70,tactics:70,people:70,youth:75,transfers:70}};api.setTestState(state);

const career=api.ensureCoachCareer();assert.equal(api.APP_VERSION,"V1.5");assert.equal(api.COACH_STORY_EVENTS.length,6,"coach mode needs six consequential management event types");assert.ok(api.COACH_STORY_EVENTS.every(event=>event.choices.length===3),"each coach event must offer three trade-offs");
career.nextStoryDate=state.date;const pending=api.applyCoachCareerDay(state.date);assert.equal(pending.type,"coach-career");assert.ok(api.COACH_STORY_EVENTS.some(event=>event.id===career.story.eventId),"daily progression must open a real coach event");career.story={id:"analysis-test",status:"active",eventId:"opposition-analysis",title:"对手分析会议",date:state.date,detail:"test"};api.resolveCoachStoryChoice("deep-scout");
const effect=api.coachMatchEffect();assert.ok(effect.strength>2&&effect.tactical>=5&&effect.possession>=2,"analysis decision must create a real multi-match tactical effect");
const lineupIds=squad.slice(0,11).map(player=>player.id),match={fixture,lineupIds,opponentLineupIds:[],ourPlayers:null,coachEffect:effect,substitutions:[],minute:0};const withoutPreparation=api.teamOverallStrength({...match,coachEffect:{strength:0}},"ours");assert.ok(api.teamOverallStrength(match,"ours")>withoutPreparation+2,"preparation strength must feed the match-strength simulation");

const youth=squad.filter(player=>player.age<=21).sort((a,b)=>b.potential-a.potential)[0];career.story={id:"academy-test",status:"active",eventId:"academy-pathway",title:"青训融入方案",date:state.date,detail:"test"};api.resolveCoachStoryChoice("cup-pathway");assert.ok(career.preparations.some(item=>item.youthPriorityId===youth.id),"cup pathway must name a real young player for selection priority");
const profile={youthTrust:.4,risk:.5,rotation:.4,name:"Test"},baseline=api.matchSelectionScore(youth,fixture,profile,false,"balanced");career.preparations=career.preparations.filter(item=>item.youthPriorityId!==youth.id);const withoutPriority=api.matchSelectionScore(youth,fixture,profile,false,"balanced");assert.ok(baseline>=withoutPriority+7,"promised pathway must materially change selection scoring");

career.story={id:"medical-test",status:"active",eventId:"medical-load",title:"医疗与负荷会议",date:state.date,detail:"test"};api.resolveCoachStoryChoice("reduce-load");const medicalEffect=api.coachMatchEffect();assert.ok(medicalEffect.injuryFactor<.75,"load reduction must lower real injury probability for upcoming matches");
console.log("coach career event tests passed: consequential tactical, youth-selection, recovery and management effects");
