"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),context={console,Intl,Date,Math,setTimeout,clearTimeout,setInterval,clearInterval,localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}},document:{getElementById:()=>({}),querySelectorAll:()=>[]},navigator:{},addEventListener:()=>{},__test:{}};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,"data/dongqiudi-data.js"),"utf8"),context);
let source=fs.readFileSync(path.join(root,"app.js"),"utf8");source=source.replace(/\n  render\(\);\n\}\)\(\);\s*$/,`
  Object.assign(window.__test,{CLUBS,REAL_PLAYERS,AI_TRANSFER_MINIMUMS,createSquad,createTransferMarket,ensurePlayerContract,createAiTransferRuntimeCache,aiCanSell,aiCanPoachYoungTalent,youngBreakoutScore,transferFee,createUserClubEliteInterest,positionUnit,setTestState:value=>{state=value;},setCache:value=>{aiTransferRuntimeCache=value;}});
})();
`);vm.runInContext(source,context);const api=context.__test;
const elite=api.CLUBS.filter(club=>club.prestige>=85).sort((a,b)=>b.prestige-a.prestige)[0],small=api.CLUBS.filter(club=>elite.prestige-club.prestige>=12&&api.REAL_PLAYERS.filter(player=>player.club===club.id).length>=15).sort((a,b)=>a.prestige-b.prestige)[0],base=api.REAL_PLAYERS.filter(player=>player.club===small.id)[0];
const squad=api.createSquad(small,base);squad.forEach(player=>api.ensurePlayerContract(player,2026));const grouped=Object.groupBy(squad,player=>api.positionUnit(player.position)),role=Object.keys(grouped).find(key=>grouped[key].length>api.AI_TRANSFER_MINIMUMS[key]),group=grouped[role];assert.ok(group?.length>api.AI_TRANSFER_MINIMUMS[role]);const talent=group.sort((a,b)=>b.overall-a.overall)[0];talent.age=20;talent.overall=Math.max(72,small.prestige+3);talent.potential=Math.max(88,talent.overall+10);talent.appearances=24;talent.ratingTotal=174;talent.goals=6;talent.assists=9;talent.development={...(talent.development||{}),minutes:1800};talent.contract.endSeason=2027;talent.contract.role="核心主力";talent.value=18;
const save={version:33,role:"player",clubId:small.id,controlledId:"someone-else",squad,season:2026,date:"2027-01-05",played:24,funds:20,media:[],notifications:[],transferHistory:[],transferRequestsLog:[],transferNegotiations:[],transferMarket:api.createTransferMarket(2026)};api.setTestState(save);const cache=api.createAiTransferRuntimeCache(save,save.date);api.setCache(cache);
assert.equal(api.aiCanSell(save,small.id,talent,group),false,"ordinary squad-clearing rules should protect the core talent");assert.ok(api.youngBreakoutScore(save,talent,small,elite,save.date)>=25,"performance and potential should qualify as a breakout");assert.equal(api.aiCanPoachYoungTalent(save,small.id,talent,elite,group,save.date),true,"elite club must be able to pursue a protected breakout talent");
const ordinary={...talent,id:"ordinary",age:22,potential:talent.overall+2,appearances:3,ratingTotal:18,goals:0,assists:0,development:{minutes:130},contract:{...talent.contract,endSeason:2029}};assert.equal(api.youngBreakoutScore(save,ordinary,small,elite,save.date),-Infinity,"low-potential player must not qualify");assert.ok(api.transferFee(talent,elite,small,1,save)>Number(talent.value),"small club must demand a youth-performance premium");save.controlledId=talent.id;assert.equal(api.aiCanPoachYoungTalent(save,small.id,talent,elite,group,save.date),false,"controlled player must never be auto-sold");Object.keys(save.transferMarket.budgets).forEach(id=>{if(api.CLUBS.find(club=>club.id===id)?.prestige>=82)save.transferMarket.budgets[id]=500;});const interest=api.createUserClubEliteInterest(save,save.date);assert.ok(interest?.eliteInterest&&interest.advisoryOnly,"controlled breakout should receive elite interest without an automatic sale");assert.ok(save.notifications.some(item=>/豪门关注/.test(item.title)),"elite interest must be visible to the player");
console.log("elite talent poaching tests passed");
