"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),context={console,Intl,Date,Math,setTimeout,clearTimeout,setInterval,clearInterval,localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}},document:{getElementById:id=>id==="toast-region"?{appendChild:()=>{}}:{},querySelectorAll:()=>[],createElement:()=>({remove:()=>{}})},navigator:{},addEventListener:()=>{},__test:{}};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,"data/dongqiudi-data.js"),"utf8"),context);
let source=fs.readFileSync(path.join(root,"app.js"),"utf8");source=source.replace("  function render() {\n","  function render() { return; }\n  function renderDisabled() {\n");source=source.replace(/\n  render\(\);\n\}\)\(\);\s*$/,`\n  Object.assign(window.__test,{CLUBS,matchReportForFixture,archiveSeasonFixtures,selectedFixtureArchive,renderFixtures,renderModal,openFixtureReport,setTestState:value=>{state=value;},getModal:()=>modal});\n})();\n`);vm.runInContext(source,context);

const api=context.__test,club=api.CLUBS[0],opponent=api.CLUBS[1],fixture={id:"history-match-1",date:"2027-05-20",competition:"英超",round:"第 38 轮",opponent:opponent.name,home:true,status:"played",score:{home:3,away:1}},stats={possession:55,shots:14,onTarget:7,xg:2.1,corners:5,fouls:9,yellow:1,red:0},report={id:"report-history-match-1",fixtureId:fixture.id,season:2026,clubId:club.id,date:fixture.date,competition:fixture.competition,round:fixture.round,teamName:club.name,homeName:club.name,awayName:opponent.name,score:{home:3,away:1},homeStats:stats,awayStats:{...stats,possession:45,shots:8,onTarget:3,xg:.9},mvp:{id:"mvp",name:"Test MVP",rating:8.2,ours:true},ratings:[],substitutions:[],injuries:[],heatmapSummary:[]};
const state={version:41,role:"coach",person:"Archive Coach",clubId:club.id,season:2026,date:"2027-05-21",view:"fixtures",schedule:[fixture],fixtureArchives:[],fixtureSeasonFilter:"current",fixtureFilter:"all",matchReports:[report],notifications:[],squad:[]};api.setTestState(state);

assert.equal(api.matchReportForFixture(fixture).id,report.id,"legacy fixtures must find reports by fixture id even before reportId is backfilled");
assert.match(api.renderFixtures(),new RegExp(`data-match-report="${report.id}"`),"played current-season rows must expose the report interaction");
const archive=api.archiveSeasonFixtures(state);assert.equal(archive.fixtures.length,1);assert.equal(archive.fixtures[0].reportId,report.id,"season archive must persist the report link");
state.season=2027;state.schedule=[];state.fixtureSeasonFilter="season-2026";const selected=api.selectedFixtureArchive();assert.equal(selected.current,false);assert.equal(selected.season,2026);const historyHtml=api.renderFixtures();assert.match(historyHtml,/2026\/27 比赛记录/);assert.match(historyHtml,/点击查看赛后分析/);assert.match(historyHtml,new RegExp(`data-match-report="${report.id}"`));
api.openFixtureReport(report.id);assert.equal(api.getModal().type,"matchReport");assert.equal(api.getModal().id,report.id,"clicking a result must open the exact historical report");const modalHtml=api.renderModal();assert.match(modalHtml,/2026\/27/);assert.ok(modalHtml.includes(`${report.homeName} 3-1 ${report.awayName}`));assert.match(modalHtml,/比赛数据/);
assert.match(source,/archiveSeasonFixtures\(state\);[\s\S]*state\.season\+\+/,"season settlement must archive the completed schedule before replacing it");
assert.match(source,/state\.matchReports=state\.matchReports\.slice\(0,1200\)/,"report retention must cover long multi-season careers");
console.log("fixture history tests passed: current result links, season archive, historical navigation and report retention");
