"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),elements={app:{innerHTML:""},"toast-region":{appendChild:()=>{}},"busy-region":{setAttribute:()=>{},innerHTML:""}},context={console,Intl,Date,Math,setTimeout,clearTimeout,setInterval,clearInterval,localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}},document:{getElementById:id=>elements[id]||null,querySelectorAll:()=>[],createElement:()=>({remove:()=>{}})},navigator:{},addEventListener:()=>{},__test:{}};context.window=context;vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(root,"data/dongqiudi-data.js"),"utf8"),context);
let source=fs.readFileSync(path.join(root,"app.js"),"utf8");source=source.replace(/\n  render\(\);\n\}\)\(\);\s*$/,`\n  Object.assign(window.__test,{APP_VERSION,CLUBS,REAL_PLAYERS,createSquad,ensurePlayerContract,ensurePlayerCareer,createTransferMarket,createPlayerLoanOffer,completeControlledPlayerTransfer,submitPlayerSigningSuggestion,transferRecommendations,newSeason,setTestState:value=>{state=value;}});\n})();\n`);vm.runInContext(source,context);
const api=context.__test;assert.equal(api.APP_VERSION,"V1.5");
const seller=api.CLUBS.filter(club=>club.prestige>=68&&club.prestige<=82)[0],sourcePlayer=api.REAL_PLAYERS.filter(player=>player.club===seller.id).sort((a,b)=>a.overall-b.overall)[0],squad=api.createSquad(seller,sourcePlayer);squad.forEach(player=>api.ensurePlayerContract(player,2026));const player=squad.find(item=>item.id==="controlled");
const state={version:37,role:"player",person:player.name,clubId:seller.id,controlledId:"controlled",squad,season:2026,date:"2026-07-01",view:"home",schedule:[],notifications:[],media:[],history:[],honors:[],transferHistory:[],transferRequestsLog:[],transferNegotiations:[],funds:100,wins:0,draws:0,losses:0,points:0,leaguePosition:5,competitionProgress:{europe:{},cups:{},international:{}},transferMarket:api.createTransferMarket(2026)};Object.keys(state.transferMarket.budgets).forEach(id=>{state.transferMarket.budgets[id]=9999;});api.setTestState(state);
const career=api.ensurePlayerCareer(state);career.trust=100;career.relationships.coach=100;const recommendations=api.transferRecommendations(12);let adopted=false;for(const target of recommendations){if(api.submitPlayerSigningSuggestion(target)){adopted=true;break;}}assert.equal(adopted,true,"strong-trust player suggestion should produce at least one adopted target");assert.ok(state.transferMarket.rumors.some(item=>item.toId===seller.id&&item.status==="active"&&!item.advisoryOnly&&item.reason.startsWith("球员建议补强")),"adopted suggestion must enter the executable transfer market");
career.loanSearchUntil="2026-08-01";const loan=api.createPlayerLoanOffer(state,state.date);assert.ok(loan,"an approved external-loan search should produce a formal loan offer");assert.equal(loan.loan,true);assert.equal(api.completeControlledPlayerTransfer(loan),true);assert.equal(career.loanParentClubId,seller.id);assert.notEqual(state.clubId,seller.id);const loanClub=state.clubId,loanPlayer=state.squad.find(item=>item.id==="controlled");loanPlayer.appearances=12;loanPlayer.goals=3;loanPlayer.assists=4;loanPlayer.ratingTotal=82.8;state.schedule=[];state.date="2027-05-20";career.loanEndSeason=2026;api.newSeason();assert.equal(state.clubId,seller.id,"loaned player must return to parent club at season transition");assert.equal(career.loanParentClubId,null);assert.ok(state.transferHistory.some(item=>item.type==="loan-return"&&item.fromId===loanClub&&item.toId===seller.id));assert.ok(state.squad.find(item=>item.id==="controlled").careerStats.some(item=>item.clubId===loanClub&&item.appearances===12),"loan spell data must remain in career history");
console.log("meaningful choice tests passed: V1.5, executable suggestion, formal loan, automatic return and preserved history");
