"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),written=new Map(),toasts=[];let attempts=0;
const storage={getItem:key=>written.get(key)||null,setItem(key,value){attempts++;if(key.includes("save-slot")&&attempts===1){const error=new Error("quota");error.name="QuotaExceededError";throw error;}written.set(key,value);},removeItem:key=>written.delete(key)};
const context={console,Intl,Date,Math,setTimeout,clearTimeout,setInterval,clearInterval,localStorage:storage,document:{getElementById:id=>id==="toast-region"?{appendChild:element=>toasts.push(element.textContent)}:{},querySelectorAll:()=>[],createElement:()=>({className:"",textContent:"",remove:()=>{}}),body:{classList:{add:()=>{},remove:()=>{}}}},navigator:{},addEventListener:()=>{},__test:{}};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,"data/dongqiudi-data.js"),"utf8"),context);
let source=fs.readFileSync(path.join(root,"app.js"),"utf8");source=source.replace(/\n  render\(\);\n\}\)\(\);\s*$/,`\n  Object.assign(window.__test,{saveState,setTestState:value=>{state=value;},setActiveSave:value=>{activeSaveId=value;}});\n})();\n`);vm.runInContext(source,context);

const api=context.__test,duplicatedSegment={clubId:"club",appearances:12,goals:4,assists:3,ratingTotal:84,keyPasses:20,segments:[]},save={version:43,role:"coach",person:"Storage Test",clubId:"club",season:2026,date:"2026-12-01",played:15,squad:[],matchReports:Array.from({length:500},(_,index)=>({id:`report-${index}`})),fixtureArchives:Array.from({length:25},(_,index)=>({season:2026-index})),media:Array.from({length:100},(_,index)=>({id:index})),notifications:Array.from({length:80},(_,index)=>({id:index,read:false})),worldPlayerStats:{season:2026,players:{player:{...duplicatedSegment,segments:[{...duplicatedSegment,clubId:"club"}]}},archives:{},processedMatches:Object.fromEntries(Array.from({length:400},(_,index)=>[`match-${index}`,true]))}};
api.setTestState(save);api.setActiveSave("quota-test");assert.doesNotThrow(()=>api.saveState(),"quota recovery must not break navigation or game actions");
assert.ok(attempts>=2,"save must retry after compacting");assert.ok(written.has("football-simulator-save-slot-quota-test"),"compacted save must be persisted");assert.equal(save.worldPlayerStats.players.player.segments.length,0,"duplicate live club segments must be removed");assert.ok(Object.keys(save.worldPlayerStats.processedMatches).length<=120);assert.equal(save.matchReports.length,260);assert.equal(save.fixtureArchives.length,12);assert.equal(save.media.length,40);assert.equal(save.notifications.length,30);assert.ok(toasts.includes("存档数据已压缩，操作可以继续"));

console.log("storage quota recovery tests passed: compact, retry and non-blocking navigation");
