"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),elements={app:{innerHTML:""},"toast-region":{appendChild:()=>{}}},context={console,Intl,Date,Math,setTimeout,clearTimeout,setInterval,clearInterval,localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}},document:{getElementById:id=>elements[id]||null,querySelectorAll:()=>[],createElement:()=>({className:"",textContent:"",remove:()=>{}})},navigator:{},addEventListener:()=>{},__test:{}};context.window=context;vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(root,"data/dongqiudi-data.js"),"utf8"),context);
let source=fs.readFileSync(path.join(root,"app.js"),"utf8");source=source.replace(/\n  render\(\);\n\}\)\(\);\s*$/,
`\n  Object.assign(window.__test,{CLUBS,REAL_PLAYERS,createSquad,ensurePlayerContract,createTransferMarket,createAiTransferRuntimeCache,transferTickDelay,createUnsolicitedControlledPlayerOffer,createUserClubExternalOffer,acceptUserClubExternalOffer,renderModal,setTestState:value=>{state=value;},setModal:value=>{modal=value;},setCache:value=>{aiTransferRuntimeCache=value;}});\n})();\n`);
vm.runInContext(source,context);const api=context.__test;

for(const date of ["2026-06-16","2026-07-10","2026-08-12","2026-08-28"])assert.ok(api.transferTickDelay(date,2026)<=2,`summer market should re-evaluate within two days (${date})`);
const club=api.CLUBS.filter(item=>item.prestige>=70&&item.prestige<=80).sort((a,b)=>a.prestige-b.prestige)[0],sourcePlayer=api.REAL_PLAYERS.filter(player=>player.club===club.id).sort((a,b)=>b.overall-a.overall)[0];
function baseSquad(){const squad=api.createSquad(club,sourcePlayer);squad.forEach(player=>api.ensurePlayerContract(player,2026));return squad;}
function fundedMarket(){const market=api.createTransferMarket(2026);Object.keys(market.budgets).forEach(id=>{market.budgets[id]=9999;});return market;}

const playerSquad=baseSquad(),controlled=playerSquad.find(item=>item.id==="controlled");Object.assign(controlled,{overall:Math.max(78,controlled.overall),potential:91,appearances:20,ratingTotal:145,value:35,development:{...(controlled.development||{}),minutes:1650}});controlled.contract.endSeason=2027;
const playerSave={version:36,role:"player",person:controlled.name,clubId:club.id,controlledId:"controlled",squad:playerSquad,season:2026,date:"2026-07-01",played:20,schedule:[],notifications:[],media:[],transferHistory:[],transferRequestsLog:[],transferNegotiations:[],transferMarket:fundedMarket()};api.setTestState(playerSave);
let playerOffer=null;for(let day=1;day<=31&&!playerOffer;day++){playerSave.date=`2026-07-${String(day).padStart(2,"0")}`;api.setCache(api.createAiTransferRuntimeCache(playerSave,playerSave.date));playerOffer=api.createUnsolicitedControlledPlayerOffer(playerSave,playerSave.date);api.setCache(null);}assert.ok(playerOffer,"an in-form player should receive an unsolicited formal offer during an active window");assert.equal(playerOffer.status,"active");

const coachSave={version:36,role:"coach",person:"测试主教练",clubId:club.id,controlledId:null,squad:baseSquad(),season:2026,date:"2026-07-01",view:"transfers",played:14,schedule:[],notifications:[],media:[],transferHistory:[],transferRequestsLog:[],transferNegotiations:[],transferMarket:fundedMarket()};coachSave.squad.forEach((player,index)=>{player.appearances=index<16?12:4;player.ratingTotal=player.appearances*6.8;});api.setTestState(coachSave);
let clubOffer=null;for(let day=1;day<=31&&!clubOffer;day++){coachSave.date=`2026-07-${String(day).padStart(2,"0")}`;api.setCache(api.createAiTransferRuntimeCache(coachSave,coachSave.date));clubOffer=api.createUserClubExternalOffer(coachSave,coachSave.date);api.setCache(null);}assert.ok(clubOffer,"coach career should receive an external club offer during an active window");api.setModal({type:"userClubOffer",id:clubOffer.id});const html=api.renderModal();for(const text of ["外部正式报价","转会费","接受报价","拒绝报价"])assert.match(html,new RegExp(text),`coach offer modal should show ${text}`);
const offeredPlayer=coachSave.squad.find(player=>player.id===clubOffer.sourcePlayerId),beforeSquadSize=coachSave.squad.length;api.acceptUserClubExternalOffer(clubOffer.id);assert.equal(clubOffer.status,"completed","coach should be able to accept an external offer");assert.equal(coachSave.squad.length,beforeSquadSize-1,"accepted external offer should remove the player from the squad");assert.ok(coachSave.transferHistory.some(record=>record.playerName===offeredPlayer.name&&record.toId===clubOffer.toId),"accepted offer must enter transfer history");
console.log("transfer market activity tests passed");
