"use strict";

const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),elements={app:{innerHTML:""},"toast-region":{appendChild:()=>{}},"busy-region":{setAttribute:()=>{},innerHTML:""}},context={console,Intl,Date,Math,setTimeout,clearTimeout,setInterval,clearInterval,localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}},document:{getElementById:id=>elements[id]||null,querySelectorAll:()=>[],createElement:()=>({remove:()=>{}})},navigator:{},addEventListener:()=>{},__test:{}};context.window=context;vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(root,"data/dongqiudi-data.js"),"utf8"),context);
let source=fs.readFileSync(path.join(root,"app.js"),"utf8");source=source.replace(/\n  render\(\);\n\}\)\(\);\s*$/,`\n  Object.assign(window.__test,{CLUBS,LEAGUES,EUROPEAN_COMPETITIONS,createSquad,ensurePlayerContract,createMajorLeagueWorld,createWorldHistory,archiveWorldSeasonAndApplyPromotion,ensureWorldHistory,clubHonors,generateSchedule,renderClubProfileModal,renderWorld,leaguePositionZone,setTestState:value=>{state=value;}});\n})();\n`);vm.runInContext(source,context);
const api=context.__test,club=api.CLUBS.find(item=>item.league==="ENG2");assert.ok(club,"English second tier must exist");const squad=api.createSquad(club);squad.forEach(player=>api.ensurePlayerContract(player,2026));const assignments=Object.fromEntries(api.CLUBS.map(item=>[item.id,item.league])),countsBefore=Object.fromEntries(Object.keys(api.LEAGUES).map(id=>[id,api.CLUBS.filter(club=>club.league===id).length]));
const state={version:38,role:"coach",person:"World Test",clubId:club.id,squad,season:2026,date:"2027-05-30",view:"world",schedule:[],played:46,wins:38,draws:4,losses:4,points:118,leaguePosition:1,honors:[{name:`${api.LEAGUES.ENG2.name}冠军`,season:2026,scope:"俱乐部"}],history:[],notifications:[],media:[],transferHistory:[],transferRequestsLog:[],transferNegotiations:[],competitionProgress:{europe:{ucl:{played:8,points:12,gf:14,ga:9,position:14,eliminated:true,knockoutStage:0}},cups:{},international:{}},worldHistory:api.createWorldHistory(),worldClubLeagues:assignments,majorLeagueWorld:api.createMajorLeagueWorld(2026,club.id)};const league=state.majorLeagueWorld.leagues.ENG2;league.clubs.forEach((row,index)=>Object.assign(row,{p:46,w:12,d:10,l:24,gf:45,ga:66,gd:-21,pts:46-index}));Object.assign(league.clubs.find(row=>row.id===club.id),{p:46,w:38,d:4,l:4,gf:103,ga:28,gd:75,pts:118});api.setTestState(state);
const settlement=api.archiveWorldSeasonAndApplyPromotion(state),history=api.ensureWorldHistory(state);assert.ok(settlement.changes.some(change=>change.clubId===club.id&&change.fromId==="ENG2"&&change.toId==="ENG1"),"second-tier champion must be promoted");assert.equal(club.league,"ENG1");assert.equal(state.worldClubLeagues[club.id],"ENG1");for(const [leagueId,count] of Object.entries(countsBefore))assert.equal(api.CLUBS.filter(item=>item.league===leagueId).length,count,`${leagueId} membership size must remain stable`);
for(const [leagueId,config] of Object.entries(api.LEAGUES)){const record=history.competitions[config.name]?.[0];assert.ok(record,`${config.name} must receive a season record`);assert.equal(record.table.length,countsBefore[leagueId]);assert.ok(record.champion&&record.runnerUp);assert.ok(Number.isFinite(record.matches)&&Number.isFinite(record.goals));}
for(const config of Object.values(api.EUROPEAN_COMPETITIONS)){const record=history.competitions[config.fullName]?.[0];assert.ok(record,`${config.name} history must be archived`);assert.ok(record.champion&&record.runnerUp&&record.matches&&record.goals);}
assert.ok(Object.values(history.competitions).flat().some(record=>record.kind==="national"&&record.champion&&record.runnerUp),"national-team competitions must receive season history");assert.equal(history.competitions[api.LEAGUES.ENG2.name][0].championId,club.id,"the user's earned league title must own the world-history record");const honors=api.clubHonors(club),earned=honors.find(item=>item.name===`${api.LEAGUES.ENG2.name}冠军`);assert.ok(earned?.seasons.includes(2026),"earned title must appear in the club profile honor ledger");const aiLeagueRecord=history.competitions[api.LEAGUES.ENG1.name][0],aiChampion=api.CLUBS.find(item=>item.id===aiLeagueRecord.championId);assert.ok(api.clubHonors(aiChampion).some(item=>item.name===`${api.LEAGUES.ENG1.name}冠军`&&item.seasons.includes(2026)),"AI champions must expose earned honors in their club profile");const nextSchedule=api.generateSchedule(club,2027),leagueFixtures=nextSchedule.filter(fixture=>fixture.competition===api.LEAGUES.ENG1.short);assert.equal(leagueFixtures.length,api.LEAGUES.ENG1.matches,"promoted club must receive a top-flight schedule");assert.ok(leagueFixtures.every(fixture=>!api.CLUBS.find(item=>item.name===fixture.opponent)||api.CLUBS.find(item=>item.name===fixture.opponent).league==="ENG1"),"new league opponents must follow promoted membership");const profileHtml=api.renderClubProfileModal(club),worldHtml=api.renderWorld();assert.match(profileHtml,/存档：2026\/27/);assert.match(profileHtml,new RegExp(api.LEAGUES.ENG2.name));assert.match(worldHtml,/完整最终积分榜/);assert.match(worldHtml,/本队记录/);assert.match(worldHtml,/国家队记录/);assert.equal(api.leaguePositionZone(api.LEAGUES.GER1,15,18).label,"保级附加赛");assert.equal(api.leaguePositionZone(api.LEAGUES.GER1,16,18).label,"直接降级");
assert.match(worldHtml,/data-world-center="domestic"/);assert.match(worldHtml,/data-world-center="ucl"/);
state.worldCenterMode="europe";const europeanWorldHtml=api.renderWorld();assert.match(europeanWorldHtml,/world-domestic-live" hidden/);assert.match(europeanWorldHtml,/world-europe-live" >/);assert.match(europeanWorldHtml,/欧冠联赛阶段积分榜/);
state.season=2027;state.date="2028-05-30";state.honors=[];state.majorLeagueWorld=api.createMajorLeagueWorld(2027,state.clubId);api.archiveWorldSeasonAndApplyPromotion(state);assert.equal(history.competitions[api.LEAGUES.ENG1.name].length,2,"competition history must persist across seasons");assert.equal(history.competitions[api.LEAGUES.ENG1.name].map(record=>record.season).join(","),"2027,2026");for(const [leagueId,count] of Object.entries(countsBefore))assert.equal(api.CLUBS.filter(item=>item.league===leagueId).length,count,`${leagueId} membership must remain stable after repeated settlements`);
console.log(`world history tests passed: ${Object.keys(api.LEAGUES).length} leagues, ${settlement.changes.length} movements, European and national archives`);
